apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: rhdp-scheduler
spec:
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: dockerfiles/Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: rhdp-scheduler:latest
  triggers:
    - type: ConfigChange
  resources:
    limits:
      memory: 2Gi
      cpu: "1"
    requests:
      memory: 1Gi
      cpu: 500m
