apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: rhdp-scheduler
spec:
  source:
    type: Git
    git:
      uri: https://github.com/rhpds/rhdp-flow.git
      ref: main
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: dockerfiles/Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: rhdp-scheduler:latest
  triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secretReference:
          name: rhdp-flow-build-webhook
  resources:
    limits:
      memory: 2Gi
      cpu: "1"
    requests:
      memory: 1Gi
      cpu: 500m
