apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rhdp-scheduler-dev

resources:
  - ../../base

patches:
  # 1 replica, lower resources, build from main branch
  - target:
      kind: Deployment
      name: rhdp-scheduler
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 128Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 256Mi

  - target:
      kind: BuildConfig
      name: rhdp-scheduler
    patch: |
      - op: replace
        path: /spec/source/git/ref
        value: main
